### ISSUE TITLE
1.12.2 Stuck at Startup Because Pastebin Link

### ISSUE THREAD

**Issue by mk0003** [dragon-forge/HammerLib#47]
I cannot launch any **1.12.2** modpack with **HammerLib** installed. So i downloaded the source and debugged it. **DaylengthSplashes.java** file tries to download the data from https://pastebin.com/raw/U8ZNkcLV url which gets stuck for me because https://pastebin.com is blocked in my country (Türkiye).
I know this is an old version and not supported but at least it will give an idea to people who cannot start game because **HammerLib**. This problem may exists for other versions of the mod but i did not tested so i am not sure.
Is there any workaround could be done?

Thanks.

**Comment by Zeitheron** [comment]
Thanks for letting me know! Will push an update to use my own domain instead.

**Comment by ScoutTheSaneless** [comment]
has this been addressed? im also experiencing a hanging issue in 1.12.2-

**Comment by Zeitheron** [comment]
@ChaosDogG it was fixed [here](https://github.com/dragon-forge/HammerLib/commit/6097871c9dd21c8386b672b17839a7ab4d2298d4#diff-5e4854f72d4fc286860bf8dc30c639bed0f462b3ad59c507abda44ba49dc7f04L30) in 12.2.47 build

**Comment by ScoutTheSaneless** [comment]
yeah...im still hanging.....
[latest.log](https://github.com/dragon-forge/HammerLib/files/14794529/latest.log)

**Comment by ScoutTheSaneless** [comment]
am i not allocating enough RAM or...?
